STR-1506: fix EF tests docker setup  (#899)
* fix: prover-client cfg file in the docker for testing.

* fix: set rollup_name in params.json to alpn.

* fix: set timeout to 2h.

* chore: add docker logs on teardown.

* feat: check docker services before test and output logs if any failures.

* fix: adjust genesis hash in params.json.

* fix: make a separate prover-client config for testing in docker.

* chore: remove some jq hacks on params.json in workflow file.

* fix: bump workflow timeout to 4h.

* chore: setting eest against docker to run daily. also minor renames

* tmp: reduce timeout.

* chore: rename EF tests workflows to display actual meaning.

* fix: make prover-client to be built from releases/0.2.0.

* chore

* chore: final nits.

* chore: allow continue-on-error for tests step, to generate an EL proof.

* review comments.

diff --git a/.github/workflows/staging-eest.yml b/.github/workflows/staging-eest.yml
--- a/.github/workflows/staging-eest.yml
+++ b/.github/workflows/staging-eest.yml
@@ -1,18 +1,17 @@
-name: Daily Ethereum Execution Spec tests
+name: Ethereum Execution Spec tests against staging docker.
 
 on:
   schedule:
-    - cron: '0 3 * * 0'  # Weekly: Sunday 03:00 UTC
+    - cron: '0 15 * * *'  # Daily at 15:00 UTC
   workflow_dispatch:      # Manual trigger (optional)
 
 env:
-  CI: false
   COMMIT: ${{ github.sha }}
 
 permissions: {}
 
 jobs:
-  setup-services-and-run-eest:
+  setup-services-and-run-ef-tests:
     permissions:
       contents: read
       id-token: write
@@ -20,10 +19,13 @@ jobs:
     runs-on: ubuntu-latest
     environment:
       name: development
+    timeout-minutes: 120 # TODO: change to 60 once the exex witness generation is optimized.
     steps:
     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
       with:
         persist-credentials: false
+        ref: releases/0.2.0
+        fetch-depth: 0
 
     - name: Configure AWS ECR Details
       uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4
@@ -65,24 +67,9 @@ jobs:
       run: |
         docker image list
 
-    - name: Build params
-      run: |
-        # Install base58
-        pip3 install base58
-
-        # Build datatool with sp1 features
-        cargo build --bin strata-datatool --release
-
-        # Generate parameters and capture the output
-        ./target/release/strata-datatool genparams --elf-dir docker/prover-client/elfs/sp1
-        cd docker && ./init-keys.sh ../target/release/strata-datatool
-        cd configs
-
-        # Overwrite the block time for faster blocks.
-        jq '.block_time = 1000' params.json > tmp.json && mv tmp.json params.json
-
     - name: Build Prover Client image in native mode
       run: |
+        # TODO(STR-1527): fetch the prover client image (in native mode) from ECR!
         mkdir -p docker/prover-client/elfs
 
         # Build prover
@@ -90,7 +77,34 @@ jobs:
           --build-arg PROVER_FEATURES="default" \
           -t "strata-prover-client:latest" \
           -f "docker/prover-client/Dockerfile" .
-    
+
+    - name: Switch to main and do stuff
+      run: |
+        # Required because compose yml and test_ee_proof live on main so far.
+        git checkout main
+
+    - name: Build params
+      run: |
+        # TODO: consider switching to uv instead of pip3.
+        # Install base58
+        pip3 install base58
+
+        # Build datatool with sp1 features
+        cargo build --bin strata-datatool --release
+
+        # Generate params: rollup_name := alpn, block_time := 1000
+        cd docker && ./init-keys.sh ../target/release/strata-datatool -n alpn -t 1
+        cd configs
+
+        # TODO: remove once it's merged to main (init-keys are modified in the current PR).
+        # Overwrite the block time for faster blocks.
+        jq '.block_time = 1000' params.json > tmp.json && mv tmp.json params.json
+        # Overwrite the rollup_name so the sequencer is happy.
+        jq '.rollup_name = "alpn"' params.json > tmp.json && mv tmp.json params.json
+        # Override the genesis hash
+        jq '.evm_genesis_block_hash = "37ad61cff1367467a98cf7c54c4ac99e989f1fbb1bc1e646235e90c065c565ba"' params.json > tmp.json && mv tmp.json params.json
+        cat params.json
+
     - name: Start services with Docker Compose
       run: |
         docker image list
@@ -99,7 +113,22 @@ jobs:
     - name: Wait for services to be ready
       run: |
         sleep 60 # Ideally need some healthchecks.
-        docker ps -a
+        EXITED_CONTAINERS=$(docker ps -a --filter "status=exited" --format '{{.Names}}')
+
+        if [ -n "$EXITED_CONTAINERS" ]; then
+          echo "❌ Found exited containers:"
+          echo "$EXITED_CONTAINERS"
+
+          for name in $EXITED_CONTAINERS; do
+            echo -e "\n=== Logs for container: $name ==="
+            docker logs "$name" || echo "(No logs)"
+          done
+
+          echo "❌ One or more containers have exited. Failing step."
+          exit 1
+        else
+          echo "✅ All containers are running."
+        fi
 
     - name: Run tests
       run: |
@@ -128,4 +157,6 @@ jobs:
 
     - name: Tear down services
       if: always()
-      run: docker compose -f ./docker/docker-compose-testing.yml down
+      run: |
+        docker logs strata_prover_client
+        docker compose -f ./docker/docker-compose-testing.yml down
